spring:
  datasource:
    name: test
    url: jdbc:mysql://8.142.107.111:8796/appservice?characterEncoding=utf8&useSSL=false
    username: xht
    password: 6c2e4f~!@84e662
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  # MongoDB 配置
  data:
    mongodb:
      database: cola_demo
#      username: root
#      password: M9K4suTeQqFxuTxc#
      host: 8.142.107.111
      port: 27333
  main:
    allow-bean-definition-overriding: true

dong:
  enable: true
  username: 红红
  age: 11
  sex: 女
logging:
  level:
    org:
      springframework:
        security: debug
