spring:
  datasource:
    name: test
    url: jdbc:mysql://8.142.107.111:8796/appservice?characterEncoding=utf8&useSSL=false
    username: xht
    password: 6c2e4f~!@84e662
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
flowable:
  idm:
    app:
      admin:
        password: test
        user-id: admin
        first-name: admin
        last-name: admin